services:
  web-ui:
    image: ghcr.io/open-webui/open-webui:main
    env_file:
      - webui.env
    ports:
      - "3000:8080"
    volumes:
      - webui:/app/backend/data

  ollama:
    image: ollama/ollama #:rocm # for AMD gpu
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
    env_file:
      - ollama.env
    # AMD gpu:
    # devices:
    #   - /dev/kfd
    #   - /dev/dri
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
      - ./scripts/entrypoint.sh:/entrypoint.sh

  jupyter:
    image: jupyter/minimal-notebook:latest
    container_name: jupyter-notebook
    ports:
      - "8888:8888"
    volumes:
      - jupyter_data:/home/jovyan/work
      - ./jupyter_config:/home/jovyan/.jupyter
    env_file:
      - jupyter.env
    command: jupyter notebook --NotebookApp.disable_check_xsrf=True

volumes:
  webui:
  ollama:
  jupyter_data:
