services:
  web-ui:
    image: ghcr.io/open-webui/open-webui:main
    env_file:
      - webui.env
    ports:
      - "3000:8080"
    restart: always

    volumes:
      - webui:/app/backend/data

  ollama:
    image: ollama/ollama:rocm
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
    # For AMD GPU
    # environment:
    #   - HSA_OVERRIDE_GFX_VERSION=10.3.0
    #   - AMDGPU_TARGETS=gfx1032
    restart: always
    devices:
      - /dev/kfd
      - /dev/dri
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh

  jupyter:
    image: jupyter/minimal-notebook:latest
    container_name: jupyter-notebook
    restart: always

    ports:
      - "8888:8888"
    volumes:
      - jupyter_data:/home/jovyan/work
      - ./jupyter_config:/home/jovyan/.jupyter # Mount your config dir here

    env_file:
      - jupyter.env
    command: jupyter notebook --NotebookApp.disable_check_xsrf=True

volumes:
  webui:
  ollama:
  jupyter_data:
